version: '3'
services:
  clickhouse:
    image: clickhouse/clickhouse-server
    restart: always
    ports:
      - "8123:8123" # HTTP-порт для запросов к ClickHouse
      - "9000:9000" # HTTP-порт для запросов к ClickHouse
    environment:
      - CLICKHOUSE_PASSWORD=${CLICKHOUSE_SERVER_PASSWORD} # Пароль пользователя
